language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
services:
  - postgresql
before_script:
  - psql -c 'create database sms_api_test;' -U postgres
before_install:
  - yarn install
script:
  - yarn run test
after_success:
  - yarn run coverage
